### ISSUE TITLE
Consider Raft instead of/in addition to ETCD

### ISSUE THREAD

**Issue by araddon** [lytics/grid#125]
It would be great to have easier to get going and less dependencies, less overlap with emerging Norms in Cloud Native Distributed Compute.   
1. less dependencies (than etcd) on import / vendor.   
2. less run-time dependencies to need a server (running etcd).  
3. less overlap w Cloud Native Norms (kube, istio/envoy).

So possibly make the etcd an interface for `Coordinator` or something.  Let us say that currently etcd provides these functions:

1. Cluster Seed (find/connect an existing cluster)
2. Node/Cluster discovery and membership.  (add/remove nodes as they come & go)
3. Mailbox Discovery & Mutex
4. Durable Storage for https://github.co/lytics/flo

Since Grid started there are a few interesting things to consider in the distributed-compute space:

* *Kubernetes* more and more kube may be the new OS, so software maybe written and targeted for this os.  ie, depend on it.  Kube could provide some of the discovery that etcd provides (but not mailbox level).
* *Envoy & ISTIO* Istio/envoy are nice for allowing clients to be thinner push the tracing, backoff, discovery away from client.  Not sure we can push the mailbox mutex all the way down, but possibly with envoy similar to the countour project below?

*research items*
* https://github.com/heptio/contour interesting because usage of envoy wout istio
* Serf for Discovery  https://github.com/travisjeffery/jocko/tree/master/serf
* Embedded Raft for Mutex "Mailboxes"  https://github.com/travisjeffery/jocko/tree/master/raft  & https://github.com/rqlite/rqlite/blob/master/store/store.go

**Comment by epsniff** [comment]
I like the idea of embedding raft, as it would simplify our dependencies.  I think `Istio\envoy/kubernetes` could be components of embedding raft (discovery/seeding), but before we dive into thier functionally we should discuss what it'd take to embed raft in the general sense.

**Comment by epsniff** [comment]
##### Questions/Thoughts:

- If we embed raft, does that mean we'd need to run a min number of nodes (3) 
- How do we deal with large clusters with more than 5 nodes.  Do we using multi-raft or do we do what etcd v2 did, and any node after 5 is just a listener and doesn't participate into elections. 
- During a cold-startup, cluster starts will need to `discover` at least one seed node so that each new node can join the serf/gossip ring.   We could use use istio/k8s API for this, but I think we should make it pluggable and support any method.

**Comment by mdmarek** [comment]
Overall I like the idea. Here are a few thoughts to further the idea:

1.
Right now both the grid Server and Client take as a parameter an etcd Client. That client would be replaced with something like database/sql in terms of how parts fit together.

Specifically it would be a struct NOT an interface. There would be a driver sub-package that would allow plug-in drivers, just like database/sql/driver. The flo code is doing that here: [flo storage)[https://github.com/lytics/flo/tree/master/storage]

**Comment by mdmarek** [comment]
@araddon Have you played with the hashicorp/raft to know if the method:

```
Apply(l *raft.Log) interface{}
```

can return an error that will prevent the log entry from getting applied? That would change some of the comments I made above.

**Comment by araddon** [comment]
have not played with it, will experiment on that.

**Comment by araddon** [comment]
https://github.com/hashicorp/raft/blob/master/future.go

https://github.com/hashicorp/raft/blob/master/fsm.go#L72

**Comment by gedw99** [comment]
https://github.com/k3s-io/kine Has nats as of last week 

this gets you etcd with nats doing the raft 

It allows global etcd by just using the standard Nats tools
