### ISSUE TITLE
Add BroadCast to Grid Client

### ISSUE THREAD

**Issue by timkaye11** [lytics/grid#129]
In the case that the actor-definitions share a common prefix (eg: if the actor-defs are constructed using [ring](https://github.com/lytics/grid/tree/master/ring)), a `Broadcast` function - to send messages to the actors - would be useful. 

Proposed Design: 

The current grid `client` has functions: 
```go
Request( timeout time.Duration, receiver string, msg interface{} )
RequestC( ctx context.Context, receiver string, msg interface[} )
```

To support `Broadcast`ing, the following is proposed: 
```go
Broadcast( timeout time.Duration, g Group, msg interface{} ) (BroadcastResult, error)
BroadcastC( timeout time.Duration, g Group, msg interface{} ) (BroadcastResult, error)
```

Along with the following definitions
```go
// results for each actor
type BroadcastResult map[string]*ResultValue

func (r BroadcastResult) Add( res BroadcastResult) { // todo }

type ResultValue struct {
 Err error
 Val interface{}
}

type Group interface {
   Fastest() Group
   ExceptSuccesses([]string) Group
   Members() []string
   Close() 
}
```

To guarantee delivery to all actors: 
```go
var res, tmp Result
var err error
retry.X( maxNumRetries, func() bool  {
   tmp, err = client.Broadcast(1 * time.Second, g.ExceptSuccesses(res), msg)
   res.Add(tmp)
   return err != nil
})
```

To guarantee delivery to one (or many) actors with first-one-wins:
```go
res, err := client.Broadcast(1 * time.Second, g.Fastest(), msg)
```

@epsniff @mdmarek

**Comment by mdmarek** [comment]
@timkaye11... two requests:

 1. Change `Result` to `BroadcastResult` since it is only used there, and changes the original pattern of getting the actual interface{} result, which is fine, it's just different.
 1. On the `BroadcaseResult` struct, change the method name from `Add` to `Merge`.

**Comment by timkaye11** [comment]
good call @mdmarek: I updated the code-snippet in the ticket description.

**Comment by mdmarek** [comment]
@timkaye11 One more request, can we change `List` method in `Group` to be `Members`. Also `Group` itself should just be a struct.
