### ISSUE TITLE
Unable to replicate examples using Gin-Gonic, but can with using regular http library, 

### ISSUE THREAD

**Issue by postables** [lytics/grid#134]
I've begun playing around with the grid library, and went about replicating the examples. While trying the `requestreply` example, I opted to use my go-to API package `gin-gonic` which makes extensive use of context. I believe this use of context is what's causing issues communicating to leaders, and workers as I get the following error:

```
2018/08/25 18:55:14 [Recovery] 2018/08/25 - 18:55:14 panic recovered:
POST /api/v1/ethereum/generate/distributed/worker-2 HTTP/1.1
Host: 127.0.0.1:6767
Accept: */*
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 171
Content-Type: multipart/form-data; boundary=--------------------------400256457405561121128143
Postman-Token: d95ed76d-da34-43fc-9171-96c94a8e80b7
User-Agent: PostmanRuntime/7.1.5


runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:502 (0x42b808)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:63 (0x42a87d)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/signal_unix.go:388 (0x440a29)
	sigpanic: panicmem()
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/lytics/grid/client.go:154 (0xadd727)
	(*Client).RequestC: nsReceiver, err := namespaceName(Mailboxes, c.cfg.Namespace, receiver)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/lytics/grid/client.go:147 (0xadd684)
	(*Client).Request: return c.RequestC(timeoutC, receiver, msg)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/api.go:72 (0xae7e98)
	(*API).GenerateEthereumKeysDistributedly: resp, err := api.Client.Request(time.Second*2, worker, genReq)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/api.go:26 (0xaea533)
	(*API).GenerateEthereumKeysDistributedly-fm: api.Router.POST("/api/v1/ethereum/generate/distributed/:worker", api.GenerateEthereumKeysDistributedly)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/context.go:108 (0x917d52)
	(*Context).Next: c.handlers[c.index](c)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/recovery.go:48 (0x928a79)
	RecoveryWithWriter.func1: c.Next()
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/context.go:108 (0x917d52)
	(*Context).Next: c.handlers[c.index](c)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/logger.go:84 (0x927d2b)
	LoggerWithWriter.func1: c.Next()
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/context.go:108 (0x917d52)
	(*Context).Next: c.handlers[c.index](c)
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/gin.go:361 (0x91fd65)
	(*Engine).handleHTTPRequest: c.Next()
/home/solidity/go/src/github.com/RTradeLtd/VaaS/vendor/github.com/gin-gonic/gin/gin.go:326 (0x91f5b2)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2694 (0x6674ab)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1830 (0x663600)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:2361 (0x4584c0)
	goexit: BYTE	$0x90	// NOP
```

Grid Code: https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/distributor.go
API Code: https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/api.go

**Comment by jonasagx** [comment]
Looking at your logs it looks like your client config ClientCfg is nil. Your repo has C dependencies that keep me from reproducing it.

**Comment by jonasagx** [comment]
I would say: try playing with the library a little more before you inject it as part of your projects,

**Comment by mdmarek** [comment]
@postables I'm not sure which commit you are using, of the VaaS project, but taking a quick look around I see that the call to InitializeAPI here:

https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/main.go

Is called with a `nil` client.

Am I reading that right?

**Comment by mdmarek** [comment]
@postables How are you initializing the grid client in `api.go`? I see that you have the `InitializeAPI` function, but who is calling that to do the initialization, and the client that is being passed in, how is that client created?

**Comment by postables** [comment]
@mdmarek 

Everything get's initialized within this function https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/distributor.go#L110

When starting out the test I will run:
`./VaaS distributor 127.0.0.1:0`

This will then run the `InitializeDistributor` which in turn will run https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/distributor.go#L152 that passes in the `grid client` which gets generated here https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/distributor.go#L121

**Comment by araddon** [comment]
im trying to run your lib, get this:
```

**Comment by postables** [comment]
@araddon  yes you need to have go-ethereum files `go get -v github.com/ethereum/go-ethereum`

What do you mean I'm not setting? I do so with the line `api.Client = gc`

As for globally registering those two lines, I thought they already are? My main function calls `InitializeDistributor` https://github.com/RTradeLtd/VaaS/blob/3cd3fc94a3f7194126af221240d536c421c39649/main.go#L25

**Comment by postables** [comment]
I was able to get it to work with a single worker, by changing the API initialization to:
https://github.com/RTradeLtd/VaaS/blob/392a4b4e6309d59ddc04afee4ed82ce3dc640ae4/api.go#L20-L30

by changing `api.Client` to `api.client` which makes sense.
